#! /bin/bash

src="/etc/letsencrypt/archive/off.cccl.nl"
dst="/app/onlyoffice/DocumentServer/data/certs"

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

# Check if there is a new certificate and if so do a certificate rollover

if [ "$(md5sum $src/fullchain4.pem |awk '{print $1}')" = "$(md5sum $dst/onlyoffice.crt |awk '{print $1}')" ]
 then cp $src/fullchain4.pem $dst/onlyoffice.crt
      cp $src/privkey4.pem $dst/onlyoffice.key
  else exit 1
fi

# Restart the container
docker restart only_office
